name: Build Padavan

on:
  release:
    types: [published]
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-20.04
    timeout-minutes: 720

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Initialization environment
      run: |
        sudo apt-get update
        sudo apt-get upgrade -y
        sudo apt-get install -y unzip libtool-bin curl cmake gperf gawk flex bison nano xxd \
        fakeroot cpio git python3-docutils gettext automake autopoint texinfo build-essential \
        help2man pkg-config zlib1g-dev libgmp3-dev libmpc-dev libmpfr-dev libncurses5-dev libltdl-dev wget
        sudo apt-get autoremove -y && sudo apt-get clean

    - name: Clone source code
      run: |
        git clone --depth=1 https://e.coding.net/hanwckf/rt-n56u/padavan.git /opt/rt-n56u
        cd /opt/rt-n56u/toolchain-mipsel
        sh dl_toolchain.sh
        mkdir -p /opt/images/

    - name: Build Firmware
      env:
        TNAME: MI-4C
      run: |
        cd /opt/rt-n56u/trunk
        
        if [ ! -f configs/templates/$TNAME.config ]; then
          echo "型号 $TNAME 不存在！"
          exit 1
        fi
        
        cp -f configs/templates/$TNAME.config .config

        # 清理所有多余配置项
        sed -i '/CONFIG_FIRMWARE_INCLUDE/d' .config

        # 只开启：校园网 mentohust + minieap
        echo "CONFIG_FIRMWARE_INCLUDE_MENTOHUST=y" >> .config
        echo "CONFIG_FIRMWARE_INCLUDE_MINIEAP=y" >> .config

        # 编译
        ./clear_tree
        ./build_firmware_modify $TNAME 0
        
        mv -f images/*.trx /opt/images/ 2>/dev/null || true
        mv -f images/*.bin /opt/images/ 2>/dev/null || true

    - name: Upload firmware
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: Padavan-MI-4C-Mentohust-Minieap
        path: /opt/images/
